### ISSUE TITLE
RFC 1123 issue using HelmChartProxy

### ISSUE THREAD

**Issue by PlayMTL** [kubernetes-sigs/cluster-api-addon-provider-helm#262]
**What steps did you take and what happened:**
I have problems creating a HelmChartProxy for helm charts containing a "/" in the "chartName". I get the error, that the creation of the HelmReleaseProxy failed due to problems with the schema:

```message: 'failed to create HelmReleaseProxy '''' for cluster: default/my-cluster:
      HelmReleaseProxy.addons.cluster.x-k8s.io "ingress-nginx/ingress-nginx-my-cluster-jxldh"
      is invalid: [metadata.generateName: Invalid value: "ingress-nginx/ingress-nginx-my-cluster-":
      a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters,
      ''-'' or ''.'', and must start and end with an alphanumeric character (e.g.
      ''example.com'', regex used for validation is ''[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*''),
      metadata.name: Invalid value: "ingress-nginx/ingress-nginx-my-cluster-jxldh":
      a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters,
      ''-'' or ''.'', and must start and end with an alphanumeric character (e.g.
      ''example.com'', regex used for validation is ''[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'')]'
```
I have tried to fix this by using the setting "releaseName" but without success. Is any one able to help me out here?

``` 
---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: nginx-ingress
spec:
  clusterSelector:
    matchLabels:
      nginxIngressChart: enabled
  repoURL: https://kubernetes.github.io/ingress-nginx
  releaseName: nginx
  chartName: "ingress-nginx/ingress-nginx"
  version: "4.8.5"
  namespace: ingress-nginx
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    controller:
      name: "{{ .ControlPlane.metadata.name }}-nginx"
      kind: DaemonSet
      
``` 

**What did you expect to happen:**

Deployment of the helm chart in the cluster succeeds.

**Anything else you would like to add:**
%

**Environment:**

- Cluster API version: `clusterctl version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"b0284d8b9bf1220b744e8cfbfc812321c733e2dd", GitTreeState:"clean", BuildDate:"2024-06-11T10:14:56Z", GoVersion:"go1.21.11", Compiler:"gc", Platform:"linux/amd64"}` 
- Cluster API Add-on Provider for Helm version: `v0.2.4`
- minikube/kind version: `kind v0.23.0`
- Kubernetes version: (use `kubectl version`): `v1.30.0`
- OS (e.g. from `/etc/os-release`): `Ubuntu 22.04`

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
