### ISSUE TITLE
Support for private helm repositories

### ISSUE THREAD

**Issue by nikParasyr** [kubernetes-sigs/cluster-api-addon-provider-helm#30]
**User Story**

As a user i would like to be able to use private helm repositories to deploy charts. This is really necessary for charts that are built and maintained within a company and/or for air-gapped installations.

**Detailed Description**

I would expect something like this:
```
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: nginx-ingress
spec:
  clusterSelector:
    matchLabels:
      nginxIngressChart: enabled
  repoURL: https://helm.nginx.com/stable
  chartName: nginx-ingress
  credentialsRef:
    kind: Secret
    name: creds-for-private-helm-repo
```
Basically in the secret will be stored like username/pass to auth with the private helm repo.

**Anything else you would like to add:**

This might be already possible but i couldn't find something in the quick start and from a quick look in the code.

/kind feature

**Comment by Jont828** [comment]
This is a pretty interesting case, I haven't tried using private Helm repos but don't think it's currently supported. I'm wondering if we need to add an extra field or if the controller can be "smart" enough to figure it out. Would you need a secret ref to install a private Helm chart through `helm install`? Or would it just work automatically?

**Comment by nikParasyr** [comment]
I think I was a bit too fast to suggest adding a credentialsRef. I think it will be better to make the controller "smart" enough and it should be possible.

> Would you need a secret ref to install a private Helm chart through helm install? Or would it just work automatically?

Not a helm guru here so take it with a grain of salt.
This depends a bit on how `helm install` is run. 
If you do a `helm repo add` beforehand with the credentials and you install by chart reference: `helm install mymaria example/mariadb` then helm is "smart" enough to use the credentials passed during `helm repo add`.  The credentials are stored at `~/.config/helm/repositories.yaml` by default together with repo url etc. The location of the file can be different using the `--repository-config` flag.
If you install a chart using absolute url or using the `--repo` flag then you also need to pass the credentials using `--password` flag etc.

I'm not sure how CAAPH is handling it now, if the repo is added when a HCP resource is made etc.

An example of `~/.config/helm/repositories.yaml`:
```
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: traefik
  pass_credentials_all: false
  password: ""
  url: https://traefik.github.io/charts
  username: ""
- (more entries...)
```


I think it should be possible to make the controller smart enough to figure it out:
- An operator could pass a list of helm repos/creds etc. The controller checks that list before adding a helm repo. If the helm repo is in that list then it adds the repo using the credentials etc of that list
- An operator could mount a secret similar to `~/.config/helm/repositories.yaml`. The controller then checks if a helm repo is listed in that file and uses that config file for helm operations passing the `--repository-config` flag.
- ... Various way to tackle this depending on the current CAAPH implementation

( I'll try to mount a secret on `~/.config/helm/repositories.yaml`  and see how that goes. I'm expecting errors to occur during a possible `helm repo add` )
