### ISSUE TITLE
Unable to install charts containing forward slashes ("/") in their names

### ISSUE THREAD

**Issue by networkhell** [kubernetes-sigs/cluster-api-addon-provider-helm#313]
**What steps did you take and what happened:**
Helm chart with a "/" in the chart name fail to install because the generated name of the corresponding HelmReleaseProxy also contains this "/" which is a forbidden character in regards to kubernetes object naming (RFC 1123).  And there are many charts containing slashes - like the official Calico and Cilium charts. 
Am I missing the option to set the name of HelmReleaseProxy manually? 

**What did you expect to happen:**
I expect that chart installation does not fail regardless of the chart name. Either by being able to specify the name of the HelmReleaseProxy or by replacing forbidden characters in the chart name.

**Anything else you would like to add:**
Example HelmChartProxy:
```yaml
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: openstack-cloud-controller-manager
  namespace: capi-mgt-nonprod
spec:
  clusterSelector:
    matchLabels:
      helmAddonOccm: enabled
  repoURL: https://kubernetes.github.io/cloud-provider-openstack
  chartName: cpo/openstack-cloud-controller-manager
  version: 2.31.1
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    secret:
      enabled: true
      name: ccm-cloud-config
      create: false
```

Corresponding Error Message: 
```
kubectl get helmchartproxies.addons.cluster.x-k8s.io -n capi-mgt-nonprod -o wide
NAME                                 READY   REASON                           MESSAGE
calico                               True
cilium                               True
openstack-cloud-controller-manager   False   HelmReleaseProxyCreationFailed   failed to create HelmReleaseProxy '' for cluster: capi-mgt-nonprod/mgmt-nonprod-op-capi-cluster: HelmReleaseProxy.addons.cluster.x-k8s.io "cpo/openstack-cloud-controller-manager-mgmt-nonprod-op-capvtjt5" is invalid: [metadata.generateName: Invalid value: "cpo/openstack-cloud-controller-manager-mgmt-nonprod-op-capi-cluster-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "cpo/openstack-cloud-controller-manager-mgmt-nonprod-op-capvtjt5": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Environment:**

- Cluster API version: 1.8.5
- Cluster API Add-on Provider for Helm version: v0.2.6
- minikube/kind version: kind v0.25.0
- Kubernetes version: (use `kubectl version`): v1.31.2
- OS (e.g. from `/etc/os-release`): Flatcar Container Linux 3975.2.1

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
