### ISSUE TITLE
Setup HTTP_PROXY / HTTPS_PROXY and NO_PROXY for helm provider

### ISSUE THREAD

**Issue by jfpucheu** [kubernetes-sigs/cluster-api-addon-provider-helm#397]
**User Story**

As a operator I would like a way to push a proxy configuration to Helm provider because my clusters don't have direct access to internet.

**Detailed Description**

Today there is no way to setup https_proxy to helm provider at install. Find a way to push this configuration using clusterctl install or other way.

**Anything else you would like to add:**

is it possible to set manual the proxy editing the deployment after install and using env vars:

 containers:

```
    env:
    - name: HTTPS_PROXY
      value: http://192.168.10.1:3128
    - name: NO_PROXY
      value: .cluster.local.,.cluster.local,.svc,10.96.0.1,172.16.0.0/12,192.168.10.0/24
    image: registry.k8s.io/cluster-api-helm/cluster-api-helm-controller:v0.3.1
```

/kind feature
