### ISSUE TITLE
Can't get clusters

### ISSUE THREAD

**Issue by andreineustroev** [kubernetes-sigs/cluster-api-addon-provider-helm#398]
**What steps did you take and what happened:**
When addon installed, I can't apply any helm charts even with empty clusterSelector: {}, I get empty matchingClusters: []

I tried to debug with

```
// listClustersWithLabels returns a list of Clusters that match the given label selector.
func (r *HelmChartProxyReconciler) listClustersWithLabels(ctx context.Context, namespace string, selector metav1.LabelSelector) (*clusterv1.ClusterList, error) {
	log := ctrl.LoggerFrom(ctx)
	clusterList := &clusterv1.ClusterList{}
	log.V(2).Info("Discovered cluster list", "list", clusterList.Items)
```
and get `list=null` in logs

**What did you expect to happen:**

I expect that argocd will be installed at all labeled clusters

**Anything else you would like to add:**

cluster
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  finalizers:
  - cluster.cluster.x-k8s.io
  labels:
    argoCDChart: enabled
    argocd.argoproj.io/instance: aneustroev-test-3
  name: test-3
  namespace: test-3
spec:
...
  controlPlaneRef:
...
  infrastructureRef:
...
status:
....
  controlPlaneReady: true
  infrastructureReady: true
  observedGeneration: 2
  phase: Provisioned
```
helmproxy
```
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  finalizers:
  - helmchartproxy.addons.cluster.x-k8s.io
  name: argocd
  namespace: caaph-system
spec:
  chartName: argo/argo-cd
  clusterSelector:
    matchLabels:
      argoCDChart: enabled
  namespace: argocd
  options:
    enableClientCache: false
    install:
      createNamespace: true
    timeout: 5m0s
    upgrade:
      maxHistory: 10
    wait: true
    waitForJobs: true
  repoURL: https://argoproj.github.io/argo-helm
status:
  conditions:
  - lastTransitionTime: "2025-05-21T08:48:07Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-05-21T08:48:07Z"
    status: "True"
    type: HelmReleaseProxiesReady
  - lastTransitionTime: "2025-05-21T08:48:07Z"
    status: "True"
    type: HelmReleaseProxySpecsUpToDate
  matchingClusters: []
  observedGeneration: 1
```

**Environment:**

helm addon installed by kustomize, from this doc https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/main/docs/quick-start.md

- Cluster API version: v1.10.1
- Cluster API Add-on Provider for Helm version: 0.3.0
- kind version: 0.25.0
- Kubernetes version: (use `kubectl version`): v1.31.2
- OS (e.g. from `/etc/os-release`):Arch Linux

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
