### ISSUE TITLE
Support for OCI based helm repositories

### ISSUE THREAD

**Issue by tuxtof** [kubernetes-sigs/cluster-api-addon-provider-helm#75]
**User Story**

As a user I would like to be able to use OCI-based registries to deploy my charts.

**Detailed Description**

Since Helm 3.8.0 OCI support is GA.

Now a Helm repository can be stored inside a OCI-based registry, it simplify the approach to distribute chart by having both chart and container in a common registry

We need to be able to define inside an HelmChartProxy an OCI Helm repo like

```
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: mychart
spec:
  clusterSelector:
    matchLabels:
      myChart: enabled
  repoURL: oci://my-harbor-registry/helm-repo
  chartName: mychart
```

We need also to be able to support any kind of private registry (auth, cert,...)

**Anything else you would like to add:**

I would expect it works out of the box

but for the moment I get the following error
```
manager E0517 17:05:23.932359       1 controller.go:326] "Reconciler error" err="error installing or updating chart with Helm on cluster cluster1: looks lik
e \"oci://my-harbor-registry/helm-repo\" is not a valid chart repository or cannot be reached: object required" controller="helmreleaseproxy" controllerGroup="addons.clust
er.x-k8s.io" controllerKind="HelmReleaseProxy" HelmReleaseProxy="default/cilium-cluster1-7x7fk" namespace="default" name="cilium-cluster1-7x7fk" reconcileID
=fc85a698-5cf0-4724-910b-dab00427499d
```

I not yet check the code

/kind feature
