### ISSUE TITLE
Is it allowed for me to deploy resources on the workload node before deploying Helm?

### ISSUE THREAD

**Issue by littleBlackHouse** [kubernetes-sigs/cluster-api-addon-provider-helm#88]
**User Story**
I would like to define some configuration resources before deploying Helm.

**Detailed Description**
When I deploy the config/samples/calico-cni.yaml. Tigera Operator allows you to define a ConfigMap named "kubernetes-services-endpoint" to modify the environment variables of Tigera Operator. However, when deploying Helm directly, this ConfigMap is not generated automatically. Therefore, you have to define it in the workload cluster first. Is there a better way for CaaPH to achieve this?

**Anything else you would like to add:**
For example, adding an optionsTemplate field to define the desired configuration resources, and deploying the resources defined in optionsTemplate before deploying the Helm resources.
```yaml
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: calico-cni
spec:
  clusterSelector:
  # Target workload clusters with specific labels.
  #  matchLabels:
  #    calicoCNI: enabled
  # Target all workload clusters.
    matchLabels: {}
  releaseName: calico
  repoURL: https://docs.tigera.io/calico/charts
  chartName: tigera-operator
  namespace: kube-system
  valuesTemplate: |
    installation:
      cni:
        type: Calico
        ipam:
          type: HostLocal
      calicoNetwork:
        bgp: Disabled
        mtu: 1350
        ipPools:{{range $i, $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}
        - cidr: {{ $cidr }}
          encapsulation: None
          natOutgoing: Enabled
          nodeSelector: all(){{end}}
  optionsTemplate: |
    apiVersion: v1
    data:
      KUBERNETES_SERVICE_HOST: example.com
      KUBERNETES_SERVICE_PORT: "6443"
    kind: ConfigMap
    metadata:
      name: kubernetes-services-endpoint
      namespace: kube-system
```

/kind feature
